### ISSUE TITLE
.Net Core version

### ISSUE THREAD

**Issue by TheSchemm** [sadomovalex/camlex#100]
Would it be possible to build and publish binaries for .net core in your nuget package as well?

**Comment by sadomovalex** [comment]
hello TheSchemm, I think it should be possible. Will try to do it but can't promise anything about exact dates. Meanwhile you may fork repository and build own instance against .Net Core.

**Comment by TheSchemm** [comment]
Awesome! Thanks for the quick response. I just thought too, that you might be able target .Net Standard 2.0 and which would tackle all .Net Core, .Net and .Net 5

**Comment by sadomovalex** [comment]
Ok, .Net Standard 2.0 also may be considered for sure.

**Comment by sadomovalex** [comment]
@TheSchemm I checked possibility to target .Net Standard 2.0 in Camlex.Client (I assume that you meant exactly client version because basic server object model version for on-prem is mostly for farm solutions which work on SP farm and of course use .Net Framework). For now I don't see big need to retarget Camlex.CLient to .Net Standard 2.0 because of 2 main reasons:

1. First reason is [.NET Framework compatibility mode](https://docs.microsoft.com/en-us/dotnet/core/porting/third-party-deps#net-framework-compatibility-mode):

> Starting with .NET Standard 2.0, the .NET Framework compatibility mode was introduced. This compatibility mode allows .NET Standard and .NET Core projects to reference .NET Framework libraries. Referencing .NET Framework libraries doesn't work for all projects, such as if the library uses Windows Presentation Foundation (WPF) APIs, but it does unblock many porting scenarios.

I've tried to reference Camlex.Client from .Net Standard 2.0 app and it worked i.e. queries were successfully created from C# code. There was this warning but it is not critical since code is actually working:

> warning NU1701: Package 'Camlex.Client.dll 4.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

2. Second reason is that Camlex.Client solution target both Sharepoint Online and on-prem CSOM using conditional referencing. But from documentation [Using CSOM for .NET Standard instead of CSOM for .NET Framework](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/using-csom-for-dotnet-standard) it says that CSOM for on-prem is available only for .Net Framework:
