### ISSUE TITLE
ContentTypeId BeginsWith - incorrect Value Type

### ISSUE THREAD

**Issue by ckvi** [sadomovalex/camlex#107]
The following Query is not achievable when using CAMLEX

```xml
<Query>
  <Where>
    <BeginsWith>
      <FieldRef Name='ContentTypeId'/>
      <Value Type='ContentTypeId'>0x00000000000000000000000000000000000000000000</Value>
    </BeginsWith>
  </Where>
</Query>
```

The following code:

```c#
Camlex.Query().Where(x => ((string)x["ContentTypeId"]).StartsWith("0x00000000000000000000000000000000000000000000"))
```
leads to the following CAML

```xml
<Query>
  <Where>
    <BeginsWith>
      <FieldRef Name='ContentTypeId'/>
      <Value Type='Text'>0x00000000000000000000000000000000000000000000</Value>
    </BeginsWith>
  </Where>
</Query>
```

The prolem with the latter is that this does not work on Lists, as it seems, that contain more than 500 entries. It simply returns no records without throwing an error. Despite that beeing a sharepoint issue, it would be great if it would be possible to get a BeginsWith-CAMLEX with Value Type='ContentTypId", so that die Query is 100% proper.

https://sharepoint.stackexchange.com/questions/275471/rest-filter-startswith-on-contenttypeid-fails-when-500-item-or-more

**Comment by sadomovalex** [comment]
@ckvi thank you for the post and sorry for delay in response. Interesting issue and solution. Didn't know that string operators (BeginsWith and Contains) also work with ContentTypeId field types. Currently mentioned query (with Value Type='ContentTypeId' ) indeed can't be achieved via Camlex. But it can be added quite easily by following change:
![2023-07-24_19-53-09](https://github.com/sadomovalex/camlex/assets/1245009/841d6dca-2169-4f36-80f9-7996bd19747a)
After that the following code will compile:
```csharp
string str = Camlex.Query().Where(x => ((DataTypes.ContentTypeId)x["ContentTypeId"]).StartsWith("0x00000000000000000000000000000000000000000000")).ToString(true);
```
and will return desired CAML:
```xml
<Query>
  <Where>
    <BeginsWith>
      <FieldRef Name="ContentTypeId" />
      <Value Type="ContentTypeId">0x00000000000000000000000000000000000000000000</Value>
    </BeginsWith>
  </Where>
</Query>
```
Even so solution looks like a hack I don't see problem of adding it to Camlex since it works and will make library more flexible. Will plan to add this change to the next release (don't have time schedule for it yet though).

**Comment by ckvi** [comment]
@sadomovalex thank you very much for your reply. We changed the line according to your instructions and everything worked as expected and so we were able to switch back to the shorter and better readable CamlEx based query. 

Yes, the BeginsWith Operator does work and we use it regularly in one of our projects because we have a lot of inherited ContentTypes which shall not be distinguished in a few queries we make. So we simply query for the base ContentTypeId.

Thanks a lot for your efforts!

**Comment by sadomovalex** [comment]
ok, good to hear) I've found some time (it's vacation season but I have laptop with me :) ) and added this change to nuget packages - so you may now get latest 5.4.2 version from nuget and use it as a reference instead of including modified Camlex source code to your project.

**Comment by ckvi** [comment]
Thanks a lot for your efforts!
