### ISSUE TITLE
Camlex.Client wont work in AppDomain with SharePoint CSOM 2013/2016

### ISSUE THREAD

**Issue by kvvinokurov** [sadomovalex/camlex#92]
Hi!

We have a system that performs the role of task scheduler. This application runs jobs from c# assemblies using AppDomain. We have a task for MS SharePoint 2013, working through CSOM. An error occurs while executing the method with the code (including the camlex code): 
 _System.MissingMethodException: Method not found: 'CamlexNET.Interfaces.IQuery CamlexNET.Interfaces.IQuery.Where(System.Linq.Expressions.Expression`1<system.func`2>)'._ 

Camlex latest version - 2.3.0

If the project changes the CSOM assembly to 14 version (SharePoint 2010), then everything works fine.

If you specify a configuration file in AppDomain with the following lines, then everything works:
`  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.SharePoint.Client" publicKeyToken="71e9bce111e9429c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-15.0.0.0" newVersion="15.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.SharePoint.Client.Runtime" publicKeyToken="71e9bce111e9429c" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-15.0.0.0" newVersion="15.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>`
Our application ignores the configuration file from the assembly file. 

I prepared a test application with an error demonstration.
[demo application](https://cloud.mail.ru/public/GoPc/KFy1o3jCA)
Password: 12345
P.S. To correctly reproduce the errors, CSOM SharePoint should not be in the GAC.

Before you start, you need to specify a Web reference with a test list in the SharePointDemoApplication project of the TestClass.cs file

Even the NUnit test produces this error if a redirect is not written in the app.config file.

Sentence:
Please divide the project into several. In one pure camlex, without links to SharePoint. In the second, there are already extension methods using SharePoint classes. From the second gather 3 NuGet package, compiled under a specific version of SharePoint.
Total:
Camlex.Client.Core
Camlex.Client.2010
Camlex.Client.2013
Camlex.Client.2016

**Comment by kvvinokurov** [comment]
Oh yes. And Camlex.Client.Online :)

**Comment by sadomovalex** [comment]
Hello kvvinokurov,
thank you for your participation. This behavior is by design: I intentionally keep only 2 dlls:
Camlex.Net.dll - for basic OM
Camlex.Client.dll - for client OM
which work for any Sharepoint version starting with SP2007. Yes it may require to add assembly binding redirections to custom apps, but inside Sharepoint context it works as is because it already has binding redirects implemented as publisher policy files: [http://sadomovalex.blogspot.com/2011/09/assembly-binding-redirect-in-sharepoint.html](http://sadomovalex.blogspot.com/2011/09/assembly-binding-redirect-in-sharepoint.html).

I'm the only developer who maintains the project at the moment and having 2 different dlls which work on all Sharepoint versions is the only realistic option for me to continue project maintenance.

**Comment by kvvinokurov** [comment]
I know about assemblyRedirect, but unfortunately we do not have the option to pass the config file. We will create separate nuget packages for different versions of SharePoint assemblies for the client version in a separate fork.

**Comment by sadomovalex** [comment]
Publicly available nuget packages (if you mean that) may confuse people - unless you will continue their maintenance and update their versions each time when basic Camlex will be updated. If you are not planning to maintain their versions it will be simpler create them for internal usage. Technically there should not be problems with recompiling Camlex against Sharepoint on-prem 2010, 2013, 2016 and Online dlls - it is compatible with all of them.
