### ISSUE TITLE
Reverse Engineering not working

### ISSUE THREAD

**Issue by alps2677** [sadomovalex/camlex#95]
I am trying to below caml query result not come same as online.
 string q =
                "<Query><Where><And><Lt><FieldRef Name=\"ID\" /><Value Type=\"Counter\">5000</Value></Lt><Eq><FieldRef Name=\"Title\" /><Value Type=\"Text\">View</Value></Eq></And></Where></Query>";
            var exp = Camlex.QueryFromString(q).ToExpression();

i am getting below output-Query().Where(x => ((x.get_Item("ID") < Convert(Convert("5000"))) AndAlso (Convert(x.get_Item("Title")) == "View")))

when do http://camlex-online.org/ i got below output

Camlex.Query().Where(x => x["ID"] < (DataTypes.Counter)"5000" && (string)x["Title"] == "View")

**Comment by sadomovalex** [comment]
hello,
Camlex reverse engineering returns result as Expression tree. In order to show this Expression tree and C# code another open source library is used: expression2code. See details here: [https://www.codeproject.com/Articles/311203/Camlex_NET_2_0.aspx](https://www.codeproject.com/Articles/311203/Camlex_NET_2_0.aspx).
